// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZterFtgNI0G6BkRL4boJckKyC6LK2XP4',
    appId: '1:732880967569:web:374b55eb51052bd2156c30',
    messagingSenderId: '732880967569',
    projectId: 'shopease-98390',
    authDomain: 'shopease-98390.firebaseapp.com',
    storageBucket: 'shopease-98390.firebasestorage.app',
    measurementId: 'G-HQVYY0GH8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnCDrbh4xvJUYPQuY4LfX40fWxnPP1cKk',
    appId: '1:732880967569:android:83680c1d8b10d542156c30',
    messagingSenderId: '732880967569',
    projectId: 'shopease-98390',
    storageBucket: 'shopease-98390.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuXwu4hrklnU6TjAhXyNCGxY52cZDtHLA',
    appId: '1:732880967569:ios:483b6d7cbd034e28156c30',
    messagingSenderId: '732880967569',
    projectId: 'shopease-98390',
    storageBucket: 'shopease-98390.firebasestorage.app',
    iosBundleId: 'com.example.shopease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuXwu4hrklnU6TjAhXyNCGxY52cZDtHLA',
    appId: '1:732880967569:ios:483b6d7cbd034e28156c30',
    messagingSenderId: '732880967569',
    projectId: 'shopease-98390',
    storageBucket: 'shopease-98390.firebasestorage.app',
    iosBundleId: 'com.example.shopease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZterFtgNI0G6BkRL4boJckKyC6LK2XP4',
    appId: '1:732880967569:web:415e53d78bc54499156c30',
    messagingSenderId: '732880967569',
    projectId: 'shopease-98390',
    authDomain: 'shopease-98390.firebaseapp.com',
    storageBucket: 'shopease-98390.firebasestorage.app',
    measurementId: 'G-Q6H44QEEVP',
  );
}
